apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgpt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testgpt
  template:
    metadata:
      labels:
        app: testgpt
    spec:
      containers:
        - name: my-app
          image: 24shivam/testgpt
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testgpt
spec:
  type: NodePort
  selector:
    app: testgpt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
